"""Sphinx extension: generate the dosho cab/image catalog at build time.

The catalog page (``reference/cabs.rst``) is written from the *live*
``dosho.registry`` + the image manifest on the ``builder-inited`` event, so it
can never drift from the code: every registered cab appears with its resolved
container image (KEY, version, provenance) and its input/output schema, pulled
straight from the same objects the pipeline runs. There is no hand-maintained
list to keep in sync.

Both cab flavours are covered: a ``Cab`` (real binary tool) exposes
``name``/``info``/``image``/``inputs_model``/``outputs_model`` directly; a
``StepRef`` (from ``@shinobi.pystep``, e.g. a CASA task) exposes the same on its
underlying ``.step``. ``_schema_obj`` resolves whichever it is.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

_SECTIONS = ("Args:", "Arguments:", "Returns:", "Yields:", "Raises:", "Parameters:")


def _schema_obj(cab: Any) -> Any:
    """The schema-bearing object for a registry entry: the Cab itself, or a
    StepRef's underlying `.step`."""
    if getattr(cab, "inputs_model", None) is not None:
        return cab
    return getattr(cab, "step", cab)


def _summary(info: str | None) -> str:
    """First prose paragraph of an info/docstring, stopping before a napoleon
    section (``Args:``/``Returns:``/...)."""
    if not info:
        return ""
    out: list[str] = []
    for line in info.strip().splitlines():
        s = line.strip()
        if s in _SECTIONS:
            break
        if not s:
            if out:
                break
            continue
        out.append(s)
    return " ".join(out)


def _type_name(annotation: Any) -> str:
    name = getattr(annotation, "__name__", None) or str(annotation)
    return name.replace("typing.", "").replace("pathlib.", "")


def _rst_cell(text: str) -> str:
    """Neutralise the RST inline-markup characters that would break a table
    cell, so arbitrary field descriptions render literally."""
    if not text:
        return "\\-"
    for a, b in (("\\", "\\\\"), ("*", "\\*"), ("`", "\\`"), ("|", "\\|"), ("_", "\\_")):
        text = text.replace(a, b)
    return " ".join(text.split())


def _image_index() -> dict[str, dict[str, str]]:
    """resolved image ref -> {key, version, source, kind}, from the manifest."""
    from dosho import images

    idx: dict[str, dict[str, str]] = {}
    for key, entry in images.manifest["images"].items():
        ref = getattr(images, key, None)
        if not ref:
            continue
        build = entry.get("build")
        version = (
            build["version"] if build else (ref.rsplit(":", 1)[-1] if ":" in ref else "external")
        )
        idx[ref] = {
            "key": key,
            "version": str(version),
            "source": entry.get("source", ""),
            "kind": "build" if build else "ref",
        }
    return idx


def _field_table(model: Any, with_default: bool) -> list[str]:
    """A list-table of a pydantic model's fields (Field/Type[/Default]/Description)."""
    if model is None or not model.model_fields:
        return ["*(none)*", ""]
    widths = "25 20 15 40" if with_default else "30 25 45"
    lines = [".. list-table::", "   :header-rows: 1", f"   :widths: {widths}", ""]
    header = ["Field", "Type"] + (["Default"] if with_default else []) + ["Description"]
    lines.append("   * - " + header[0])
    lines += [f"     - {h}" for h in header[1:]]
    for name, field in model.model_fields.items():
        row = [f"``{name}``", f"``{_type_name(field.annotation)}``"]
        if with_default:
            row.append("*required*" if field.is_required() else f"``{field.default!r}``")
        row.append(_rst_cell(field.description or ""))
        lines.append(f"   * - {row[0]}")
        lines += [f"     - {c}" for c in row[1:]]
    lines.append("")
    return lines


def _generate(app: Any) -> None:
    from dosho import registry

    img_index = _image_index()
    lines = [
        ".. This page is generated by docs/_ext/cab_catalog.py -- do not edit by hand.",
        "",
        "Cab catalog",
        "===========",
        "",
        "Every tool registered in dosho, with the container image it resolves to and",
        "its input/output schema. Generated from the live registry and image manifest",
        "at build time, so it stays in lockstep with the code.",
        "",
    ]

    for name in sorted(registry.list_cabs()):
        obj = _schema_obj(registry.get(name))
        ref = getattr(obj, "image", None)
        meta = img_index.get(ref)

        lines += [name, "-" * len(name), ""]
        summary = _summary(getattr(obj, "info", None))
        if summary:
            lines += [summary, ""]

        command = getattr(obj, "command", None)
        if command:
            lines.append(f":Command: ``{command}``")
        if ref:
            if meta:
                image_line = (
                    f":Image: ``{ref}`` (``{meta['key']}`` {meta['version']}, {meta['kind']})"
                )
                lines.append(image_line)
                if meta["source"]:
                    lines.append(f":Source: {meta['source']}")
            else:
                lines.append(f":Image: ``{ref}``")
        lines.append("")

        lines.append("**Inputs**")
        lines.append("")
        lines += _field_table(getattr(obj, "inputs_model", None), with_default=True)
        lines.append("**Outputs**")
        lines.append("")
        lines += _field_table(getattr(obj, "outputs_model", None), with_default=False)

    out = Path(app.srcdir) / "reference" / "cabs.rst"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")


def setup(app: Any) -> dict[str, Any]:
    app.connect("builder-inited", _generate)
    return {"version": "0.1", "parallel_read_safe": True, "parallel_write_safe": True}
