"""killms -- killMS, direction-dependent calibration for radio
interferometric data (https://github.com/saopicc/killMS). Builds on top of
DDFacet (reuses dosho's `DDFACET` image as its `base`, matching killMS's
own real Dockerfile, which does `FROM bhugo/ddfacet:...` then installs
killMS into that image's venv).

Ported the same way as `ddfacet.py`: from killMS 3.3.0's own
`killMS/Parset/DefaultParset.cfg` (the same `ReadCFG.py`-based
`--Section-OptionName` format DDFacet uses -- see that module's docstring
for the parsing rules), not cult-cargo (no `killms`/`kMS` cab exists there
to cross-check against). `nom_de_guerre` preserves the `.cfg`'s literal
case (e.g. `VisData-MSName`, `SolverType`); fields with no `#type:` tag get
the same `ast.literal_eval`-or-string fallback DDFacet's own parser uses.

No outputs are modelled: killMS's real output (a `.sols.npz` solutions
file) is named from `--SkyModel-SkyModel`/`--SkyModel-Kills`-derived
defaults inside the tool itself, not a single flag-controlled path.
"""

from __future__ import annotations

from shinobi.steps.schema import ParamMeta, Policies

from dosho import images
from dosho._builder import define_cab

_FIELDS: dict[str, tuple[str, bool, object]] = {
    "vis_data_ms_name": ("str", False, None),
    "vis_data_t_chunk": ("int", False, 15),
    "vis_data_in_col": ("str", False, 'CORRECTED_DATA_BACKUP'),
    "vis_data_out_col": ("str", False, 'CORRECTED_DATA'),
    "vis_data_free_predict_gain_col_name": ("str", False, None),
    "vis_data_free_predict_col_name": ("str", False, None),
    "vis_data_parallel": ("int", False, 1),
    "sky_model_sky_model": ("str", False, None),
    "sky_model_kills": ("str", False, None),
    "sky_model_invert": ("bool", False, False),
    "sky_model_decorrelation": ("str", False, None),
    "sky_model_free_full_sub": ("int", False, 0),
    "sky_model_sky_model_col": ("str", False, None),
    "beam_beam_model": ("str", False, None),
    "beam_beam_at": ("str", False, 'facet'),
    "beam_lofar_beam_mode": ("str", False, 'AE'),
    "beam_dt_beam_min": ("int", False, 5),
    "beam_center_norm": ("bool", False, True),
    "beam_n_chan_beam_per_ms": ("int", False, 1),
    "beam_fits_file": ("str", False, 'beam_$(corr)_$(reim).fits'),
    "beam_fits_par_angle_inc_deg": ("int", False, 5),
    "beam_fitsl_axis": ("str", False, '-X'),
    "beam_fitsm_axis": ("str", False, 'Y'),
    "beam_fits_feed": ("str", False, None),
    "beam_fits_verbosity": ("int", False, 1),
    "beam_feed_angle": ("int", False, 0),
    "beam_apply_p_jones": ("int", False, 0),
    "beam_flip_visibility_hands": ("int", False, 0),
    "beam_fits_feed_swap": ("int", False, 0),
    "beam_fits_frame": ("str", False, 'altaz'),
    "image_sky_model_base_image_name": ("str", False, None),
    "image_sky_model_dico_model": ("str", False, None),
    "image_sky_model_nodes_file": ("str", False, None),
    "image_sky_model_image_predict_parset": ("str", False, None),
    "image_sky_model_over_s": ("str", False, None),
    "image_sky_model_mask_image": ("str", False, None),
    "image_sky_model_wmax": ("str", False, None),
    "image_sky_model_max_facet_size": ("str", False, None),
    "image_sky_model_min_facet_size": ("str", False, None),
    "image_sky_model_remove_ddf_cache": ("bool", False, False),
    "image_sky_model_ddf_cache_dir": ("str", False, None),
    "image_sky_model_filter_neg_comp": ("bool", False, False),
    "image_sky_model_th_solve": ("float", False, 0.0),
    "data_selection_uv_min_max": ("str", False, None),
    "data_selection_chan_slice": ("str", False, None),
    "data_selection_flag_ants": ("str", False, None),
    "data_selection_dist_max_to_core": ("float", False, 10000.0),
    "data_selection_fill_factor": ("float", False, 1.0),
    "data_selection_field_id": ("int", False, 0),
    "data_selection_ddid": ("int", False, 0),
    "weighting_resolution": ("float", False, 0.0),
    "weighting_weight_in_col": ("str", False, None),
    "weighting_weighting": ("str", False, 'Natural'),
    "weighting_robust": ("float", False, 0.0),
    "weighting_weight_uv_min_max": ("str", False, None),
    "weighting_wtuv": ("int", False, 1),
    "actions_do_plot": ("int", False, 0),
    "actions_sub_only": ("int", False, 0),
    "actions_ncpu": ("int", False, 1),
    "actions_do_bar": ("int", False, 1),
    "actions_n_thread": ("int", False, 1),
    "actions_debug_pdb": ("int", False, 1),
    "actions_update_weights": ("int", False, 1),
    "pre_apply_pre_apply_sols": ("List[str]", False, []),
    "pre_apply_pre_apply_mode": ("List[str]", False, []),
    "solutions_ext_sols": ("str", False, None),
    "solutions_clip_method": ("str", False, '[ResidAnt]'),
    "solutions_out_sols_name": ("str", False, None),
    "solutions_apply_to_dir": ("int", False, -2),
    "solutions_merge_beam_to_applied_sol": ("int", False, 0),
    "solutions_apply_mode": ("str", False, 'AP'),
    "solutions_skip_existing_sols": ("int", False, 0),
    "solutions_sols_dir": ("str", False, None),
    "compression_compression_mode": ("str", False, None),
    "compression_compression_dir_file": ("str", False, None),
    "compression_merge_stations": ("str", False, None),
    "solvers_solver_type": ("str", False, 'CohJones'),
    "solvers_precision_dot": ("str", False, 'D'),
    "solvers_pol_mode": ("str", False, 'Scalar'),
    "solvers_dt": ("int", False, 30),
    "solvers_n_chan_sols": ("int", False, 1),
    "coh_jones_n_iter_lm": ("int", False, 7),
    "coh_jones_lambda_lm": ("int", False, 1),
    "coh_jones_lambda_tk": ("float", False, 0.0),
    "kafca_n_iter_kf": ("int", False, 6),
    "kafca_lambda_kf": ("float", False, 0.5),
    "kafca_init_lm": ("int", False, 0),
    "kafca_init_l_mdt": ("int", False, 5),
    "kafca_cov_p": ("float", False, 0.1),
    "kafca_cov_q": ("float", False, 0.1),
    "kafca_power_smooth": ("float", False, 1.0),
    "kafca_ev_p_step": ("int", False, 120),
    "kafca_ev_p_step_start": ("int", False, 1),
    "kafca_evolution_sol_file": ("str", False, None),
}

_FIELD_META: dict[str, ParamMeta] = {
    "vis_data_ms_name": ParamMeta(nom_de_guerre="VisData-MSName", info=''),
    "vis_data_t_chunk": ParamMeta(nom_de_guerre="VisData-TChunk", info=''),
    "vis_data_in_col": ParamMeta(nom_de_guerre="VisData-InCol", info=''),
    "vis_data_out_col": ParamMeta(nom_de_guerre="VisData-OutCol", info=''),
    "vis_data_free_predict_gain_col_name": ParamMeta(nom_de_guerre="VisData-FreePredictGainColName", info=''),
    "vis_data_free_predict_col_name": ParamMeta(nom_de_guerre="VisData-FreePredictColName", info=''),
    "vis_data_parallel": ParamMeta(nom_de_guerre="VisData-Parallel", info=''),
    "sky_model_sky_model": ParamMeta(nom_de_guerre="SkyModel-SkyModel", info=''),
    "sky_model_kills": ParamMeta(nom_de_guerre="SkyModel-kills", info=''),
    "sky_model_invert": ParamMeta(nom_de_guerre="SkyModel-invert", info=''),
    "sky_model_decorrelation": ParamMeta(nom_de_guerre="SkyModel-Decorrelation", info=''),
    "sky_model_free_full_sub": ParamMeta(nom_de_guerre="SkyModel-FreeFullSub", info=''),
    "sky_model_sky_model_col": ParamMeta(nom_de_guerre="SkyModel-SkyModelCol", info=''),
    "beam_beam_model": ParamMeta(nom_de_guerre="Beam-BeamModel", info='None/LOFAR'),
    "beam_beam_at": ParamMeta(nom_de_guerre="Beam-BeamAt", info='tessel/facet'),
    "beam_lofar_beam_mode": ParamMeta(nom_de_guerre="Beam-LOFARBeamMode", info='A/AE'),
    "beam_dt_beam_min": ParamMeta(nom_de_guerre="Beam-DtBeamMin", info=''),
    "beam_center_norm": ParamMeta(nom_de_guerre="Beam-CenterNorm", info=''),
    "beam_n_chan_beam_per_ms": ParamMeta(nom_de_guerre="Beam-NChanBeamPerMS", info=''),
    "beam_fits_file": ParamMeta(nom_de_guerre="Beam-FITSFile", info=''),
    "beam_fits_par_angle_inc_deg": ParamMeta(nom_de_guerre="Beam-FITSParAngleIncDeg", info=''),
    "beam_fitsl_axis": ParamMeta(nom_de_guerre="Beam-FITSLAxis", info='L axis of FITS file. Minus sign indicates reverse coordinate convention.'),
    "beam_fitsm_axis": ParamMeta(nom_de_guerre="Beam-FITSMAxis", info='M axis of FITS file. Minus sign indicates reverse coordinate convention.'),
    "beam_fits_feed": ParamMeta(nom_de_guerre="Beam-FITSFeed", info=''),
    "beam_fits_verbosity": ParamMeta(nom_de_guerre="Beam-FITSVerbosity", info=''),
    "beam_feed_angle": ParamMeta(nom_de_guerre="Beam-FeedAngle", info=''),
    "beam_apply_p_jones": ParamMeta(nom_de_guerre="Beam-ApplyPJones", info='derotate visibility data (only when FITS beam is active and also time sampled)'),
    "beam_flip_visibility_hands": ParamMeta(nom_de_guerre="Beam-FlipVisibilityHands", info='apply anti-diagonal matrix if FITS beam is enabled effectively swapping X and Y or R and L and their respective hands'),
    "beam_fits_feed_swap": ParamMeta(nom_de_guerre="Beam-FITSFeedSwap", info=''),
    "beam_fits_frame": ParamMeta(nom_de_guerre="Beam-FITSFrame", info='coordinate frame for FITS beams. Currently, alt-az, equatorial and zenith mounts are supported.'),
    "image_sky_model_base_image_name": ParamMeta(nom_de_guerre="ImageSkyModel-BaseImageName", info=''),
    "image_sky_model_dico_model": ParamMeta(nom_de_guerre="ImageSkyModel-DicoModel", info=''),
    "image_sky_model_nodes_file": ParamMeta(nom_de_guerre="ImageSkyModel-NodesFile", info=''),
    "image_sky_model_image_predict_parset": ParamMeta(nom_de_guerre="ImageSkyModel-ImagePredictParset", info=''),
    "image_sky_model_over_s": ParamMeta(nom_de_guerre="ImageSkyModel-OverS", info=''),
    "image_sky_model_mask_image": ParamMeta(nom_de_guerre="ImageSkyModel-MaskImage", info=''),
    "image_sky_model_wmax": ParamMeta(nom_de_guerre="ImageSkyModel-wmax", info=''),
    "image_sky_model_max_facet_size": ParamMeta(nom_de_guerre="ImageSkyModel-MaxFacetSize", info=''),
    "image_sky_model_min_facet_size": ParamMeta(nom_de_guerre="ImageSkyModel-MinFacetSize", info=''),
    "image_sky_model_remove_ddf_cache": ParamMeta(nom_de_guerre="ImageSkyModel-RemoveDDFCache", info=''),
    "image_sky_model_ddf_cache_dir": ParamMeta(nom_de_guerre="ImageSkyModel-DDFCacheDir", info=''),
    "image_sky_model_filter_neg_comp": ParamMeta(nom_de_guerre="ImageSkyModel-FilterNegComp", info=''),
    "image_sky_model_th_solve": ParamMeta(nom_de_guerre="ImageSkyModel-ThSolve", info=''),
    "data_selection_uv_min_max": ParamMeta(nom_de_guerre="DataSelection-UVMinMax", info=''),
    "data_selection_chan_slice": ParamMeta(nom_de_guerre="DataSelection-ChanSlice", info=''),
    "data_selection_flag_ants": ParamMeta(nom_de_guerre="DataSelection-FlagAnts", info=''),
    "data_selection_dist_max_to_core": ParamMeta(nom_de_guerre="DataSelection-DistMaxToCore", info=''),
    "data_selection_fill_factor": ParamMeta(nom_de_guerre="DataSelection-FillFactor", info=''),
    "data_selection_field_id": ParamMeta(nom_de_guerre="DataSelection-FieldID", info=''),
    "data_selection_ddid": ParamMeta(nom_de_guerre="DataSelection-DDID", info=''),
    "weighting_resolution": ParamMeta(nom_de_guerre="Weighting-Resolution", info=''),
    "weighting_weight_in_col": ParamMeta(nom_de_guerre="Weighting-WeightInCol", info=''),
    "weighting_weighting": ParamMeta(nom_de_guerre="Weighting-Weighting", info=''),
    "weighting_robust": ParamMeta(nom_de_guerre="Weighting-Robust", info=''),
    "weighting_weight_uv_min_max": ParamMeta(nom_de_guerre="Weighting-WeightUVMinMax", info=''),
    "weighting_wtuv": ParamMeta(nom_de_guerre="Weighting-WTUV", info=''),
    "actions_do_plot": ParamMeta(nom_de_guerre="Actions-DoPlot", info=''),
    "actions_sub_only": ParamMeta(nom_de_guerre="Actions-SubOnly", info=''),
    "actions_ncpu": ParamMeta(nom_de_guerre="Actions-NCPU", info=''),
    "actions_do_bar": ParamMeta(nom_de_guerre="Actions-DoBar", info=''),
    "actions_n_thread": ParamMeta(nom_de_guerre="Actions-NThread", info=''),
    "actions_debug_pdb": ParamMeta(nom_de_guerre="Actions-DebugPdb", info=''),
    "actions_update_weights": ParamMeta(nom_de_guerre="Actions-UpdateWeights", info=''),
    "pre_apply_pre_apply_sols": ParamMeta(nom_de_guerre="PreApply-PreApplySols", info=''),
    "pre_apply_pre_apply_mode": ParamMeta(nom_de_guerre="PreApply-PreApplyMode", info=''),
    "solutions_ext_sols": ParamMeta(nom_de_guerre="Solutions-ExtSols", info=''),
    "solutions_clip_method": ParamMeta(nom_de_guerre="Solutions-ClipMethod", info=''),
    "solutions_out_sols_name": ParamMeta(nom_de_guerre="Solutions-OutSolsName", info=''),
    "solutions_apply_to_dir": ParamMeta(nom_de_guerre="Solutions-ApplyToDir", info=''),
    "solutions_merge_beam_to_applied_sol": ParamMeta(nom_de_guerre="Solutions-MergeBeamToAppliedSol", info=''),
    "solutions_apply_mode": ParamMeta(nom_de_guerre="Solutions-ApplyMode", info=''),
    "solutions_skip_existing_sols": ParamMeta(nom_de_guerre="Solutions-SkipExistingSols", info=''),
    "solutions_sols_dir": ParamMeta(nom_de_guerre="Solutions-SolsDir", info=''),
    "compression_compression_mode": ParamMeta(nom_de_guerre="Compression-CompressionMode", info='auto, manual'),
    "compression_compression_dir_file": ParamMeta(nom_de_guerre="Compression-CompressionDirFile", info=''),
    "compression_merge_stations": ParamMeta(nom_de_guerre="Compression-MergeStations", info=''),
    "solvers_solver_type": ParamMeta(nom_de_guerre="Solvers-SolverType", info=''),
    "solvers_precision_dot": ParamMeta(nom_de_guerre="Solvers-PrecisionDot", info=''),
    "solvers_pol_mode": ParamMeta(nom_de_guerre="Solvers-PolMode", info=''),
    "solvers_dt": ParamMeta(nom_de_guerre="Solvers-dt", info=''),
    "solvers_n_chan_sols": ParamMeta(nom_de_guerre="Solvers-NChanSols", info=''),
    "coh_jones_n_iter_lm": ParamMeta(nom_de_guerre="CohJones-NIterLM", info=''),
    "coh_jones_lambda_lm": ParamMeta(nom_de_guerre="CohJones-LambdaLM", info=''),
    "coh_jones_lambda_tk": ParamMeta(nom_de_guerre="CohJones-LambdaTk", info=''),
    "kafca_n_iter_kf": ParamMeta(nom_de_guerre="KAFCA-NIterKF", info=''),
    "kafca_lambda_kf": ParamMeta(nom_de_guerre="KAFCA-LambdaKF", info=''),
    "kafca_init_lm": ParamMeta(nom_de_guerre="KAFCA-InitLM", info=''),
    "kafca_init_l_mdt": ParamMeta(nom_de_guerre="KAFCA-InitLMdt", info=''),
    "kafca_cov_p": ParamMeta(nom_de_guerre="KAFCA-CovP", info=''),
    "kafca_cov_q": ParamMeta(nom_de_guerre="KAFCA-CovQ", info=''),
    "kafca_power_smooth": ParamMeta(nom_de_guerre="KAFCA-PowerSmooth", info=''),
    "kafca_ev_p_step": ParamMeta(nom_de_guerre="KAFCA-evPStep", info=''),
    "kafca_ev_p_step_start": ParamMeta(nom_de_guerre="KAFCA-evPStepStart", info=''),
    "kafca_evolution_sol_file": ParamMeta(nom_de_guerre="KAFCA-EvolutionSolFile", info=''),
}

killms = define_cab(
    "killms",
    "kMS.py",
    images.KILLMS,
    _FIELDS,
    field_meta=_FIELD_META,
    policies=Policies(prefix="--"),
    info="killMS: direction-dependent calibration for radio interferometric data "
    "(https://github.com/saopicc/killMS)",
)
